# Generated by Django 5.0.4 on 2024-04-19 11:53

import users.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=100, validators=[users.validation.validate_password]),
        ),
    ]
