# Generated by Django 5.0.4 on 2024-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
